services:
  - type: web
    name: mymentor-app
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/myweb-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mymentor-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: mymentor-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mymentor-db
          property: password

databases:
  - name: mymentor-db
    databaseName: mymentor
    user: mymentor_user
    plan: free
